import { readFile } from 'node:fs/promises';

import debug from 'debug';
import * as xlsx from 'xlsx';

import type { DocumentPage, FileLoaderInterface } from '../../types';
import { promptTemplate } from './prompt';

const log = debug('file-loaders:excel');

/**
 * Hard caps so one workbook cannot alone fill a model context window.
 * Full sheet dumps of large 词库/竞品表 are for tools, not for inline chat.
 */
export const EXCEL_MAX_ROWS_PER_SHEET = 200;
export const EXCEL_MAX_SHEETS = 8;
export const EXCEL_MAX_TOTAL_CHARS = 80_000;

/**
 * Converts sheet data (array of objects) to a Markdown table string.
 * Handles empty sheets and escapes pipe characters.
 */
function sheetToMarkdownTable(
  jsonData: Record<string, any>[],
  options?: { maxRows?: number; totalRows?: number },
): string {
  log('Converting sheet data to Markdown table, rows:', jsonData?.length || 0);
  if (!jsonData || jsonData.length === 0) {
    log('Sheet is empty, returning placeholder message');
    return '*Sheet is empty or contains no data.*';
  }

  // Ensure all rows have the same keys based on the first row, handle potentially sparse data
  const headers = Object.keys(jsonData[0] || {});
  log('Sheet headers:', headers);
  if (headers.length === 0) {
    log('Sheet has no headers, returning placeholder message');
    return '*Sheet has headers but no data.*';
  }

  const maxRows = options?.maxRows ?? EXCEL_MAX_ROWS_PER_SHEET;
  const totalRows = options?.totalRows ?? jsonData.length;
  const sliced = jsonData.length > maxRows ? jsonData.slice(0, maxRows) : jsonData;
  const truncated = totalRows > sliced.length;

  const headerRow = `| ${headers.join(' | ')} |`;
  const separatorRow = `| ${headers.map(() => '---').join(' | ')} |`;

  log('Building data rows for Markdown table');
  const dataRows = sliced
    .map((row) => {
      const cells = headers.map((header) => {
        const value = row[header];
        // Handle null/undefined and escape pipe characters within cells
        const cellContent =
          value === null || value === undefined ? '' : String(value).replaceAll('|', '\\|');
        return cellContent.trim(); // Trim whitespace from cells
      });
      return `| ${cells.join(' | ')} |`;
    })
    .join('\n');

  let result = `${headerRow}\n${separatorRow}\n${dataRows}`;
  if (truncated) {
    result += `\n\n*…truncated: showing first ${sliced.length} of ${totalRows} data rows. Ask for specific filters/columns or use analysis tools for the full sheet.*`;
  }
  log('Markdown table created, length:', result.length);
  return result;
}

/**
 * Loads Excel files (.xlsx, .xls) using the 'xlsx' library.
 * Each sheet becomes a DocumentPage containing a Markdown table generated by sheetToMarkdownTable.
 */
export class ExcelLoader implements FileLoaderInterface {
  async loadPages(filePath: string): Promise<DocumentPage[]> {
    log('Loading Excel file:', filePath);
    const pages: DocumentPage[] = [];
    try {
      // Use readFile for async operation compatible with other loaders
      log('Reading Excel file as buffer');
      const dataBuffer = await readFile(filePath);
      log('Excel file read successfully, size:', dataBuffer.length, 'bytes');

      log('Parsing Excel workbook');
      const workbook = xlsx.read(dataBuffer, { type: 'buffer' });
      log('Excel workbook parsed successfully, sheets:', workbook.SheetNames.length);

      const sheetNames = workbook.SheetNames;
      const sheetsToLoad = sheetNames.slice(0, EXCEL_MAX_SHEETS);
      let totalChars = 0;

      for (const sheetName of sheetsToLoad) {
        if (totalChars >= EXCEL_MAX_TOTAL_CHARS) {
          log('Stopping sheet load: EXCEL_MAX_TOTAL_CHARS reached');
          pages.push({
            charCount: 0,
            lineCount: 0,
            metadata: { sheetName: '_truncated', truncated: true },
            pageContent: `*Further sheets omitted (context budget). Workbook has ${sheetNames.length} sheets; loaded ${pages.filter((p) => p.metadata?.sheetName !== '_truncated').length}.*`,
          });
          break;
        }

        log(`Processing sheet: ${sheetName}`);
        const worksheet = workbook.Sheets[sheetName];
        // Use sheet_to_json to get array of objects for our custom markdown function
        const jsonData = xlsx.utils.sheet_to_json<Record<string, any>>(worksheet, {
          // Get formatted strings, not raw values
          defval: '',
          raw: false, // Use empty string for blank cells
        });
        log(`Sheet ${sheetName} converted to JSON, rows:`, jsonData.length);

        const remaining = Math.max(0, EXCEL_MAX_TOTAL_CHARS - totalChars);
        // Convert to markdown using YOUR helper function (row-capped)
        let tableMarkdown = sheetToMarkdownTable(jsonData, {
          maxRows: EXCEL_MAX_ROWS_PER_SHEET,
          totalRows: jsonData.length,
        });
        if (tableMarkdown.length > remaining) {
          tableMarkdown = `${tableMarkdown.slice(0, Math.max(0, remaining - 120)).trim()}\n\n*…sheet truncated to fit context budget.*`;
        }

        const lines = tableMarkdown.split('\n');
        const lineCount = lines.length;
        const charCount = tableMarkdown.length;
        log(`Sheet ${sheetName} converted to Markdown, lines: ${lineCount}, chars: ${charCount}`);

        pages.push({
          // Trim whitespace
          charCount,
          lineCount,
          metadata: {
            sheetName,
            ...(jsonData.length > EXCEL_MAX_ROWS_PER_SHEET ? { truncated: true } : {}),
          },
          pageContent: tableMarkdown.trim(),
        });
        totalChars += charCount;
        log(`Added sheet ${sheetName} as page`);
      }

      if (sheetNames.length > sheetsToLoad.length && totalChars < EXCEL_MAX_TOTAL_CHARS) {
        pages.push({
          charCount: 0,
          lineCount: 0,
          metadata: { sheetName: '_truncated', truncated: true },
          pageContent: `*…${sheetNames.length - sheetsToLoad.length} additional sheet(s) not inlined (${sheetNames.slice(EXCEL_MAX_SHEETS).join(', ')}). Ask for a specific sheet if needed.*`,
        });
      }

      if (pages.length === 0) {
        log('Excel file contains no sheets, creating empty page with error');
        pages.push({
          charCount: 0,
          lineCount: 0,
          metadata: {
            error: 'Excel file contains no sheets.',
          },
          pageContent: '',
        });
      }

      log('Excel loading completed, total pages:', pages.length);
      return pages;
    } catch (e) {
      const error = e as Error;
      log('Error encountered while loading Excel file');
      console.error(`Error loading Excel file ${filePath}: ${error.message}`);
      const errorPage: DocumentPage = {
        charCount: 0,
        lineCount: 0,
        metadata: {
          error: `Failed to load Excel file: ${error.message}`,
        },
        pageContent: '',
      };
      log('Created error page for failed Excel loading');
      return [errorPage];
    }
  }

  /**
   * Aggregates content from Excel sheets (Markdown tables).
   * Adds the sheet name as a header before each table.
   * @param pages Array of DocumentPage objects from loadPages.
   * @returns Aggregated content as a string.
   */
  async aggregateContent(pages: DocumentPage[]): Promise<string> {
    log('Aggregating content from', pages.length, 'Excel pages');
    const result = promptTemplate(pages);

    log('Excel content aggregated successfully, length:', result.length);
    return result;
  }
}
