/**
 * Shared build-profile helpers (apply + metrics + tests).
 */
import fs from 'node:fs';
import path from 'node:path';

export type BuildProfile = 'full' | 'internal';

export type ProfileEntry = {
  entry: string;
  full: string;
  internal: string;
  kind?: 'ts' | 'tsx';
};

export const CORE_PROFILE_ENTRIES: ProfileEntry[] = [
  {
    entry: 'packages/builtin-tools/src/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'packages/builtin-tools/src/register.lazy.ts',
    full: './register.lazy.full',
    internal: './register.lazy.internal',
  },
  {
    entry: 'packages/model-bank/src/modelProviders/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'packages/model-runtime/src/runtimeMap.ts',
    full: './runtimeMap.full',
    internal: './runtimeMap.internal',
  },
  {
    entry: 'apps/server/src/services/toolExecution/serverRuntimes/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'apps/server/src/routers/lambda/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'apps/server/src/routers/lambda/market/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'src/store/tool/slices/builtin/executors/index.ts',
    full: './index.full',
    internal: './index.internal',
  },
  {
    entry: 'src/spa/router/desktopRouter.config.tsx',
    full: './desktopRouter.config.full',
    internal: './desktopRouter.config.internal',
    kind: 'tsx',
  },
  {
    entry: 'src/spa/router/desktopRouter.config.desktop.tsx',
    full: './desktopRouter.config.desktop.full',
    internal: './desktopRouter.config.desktop.internal',
    kind: 'tsx',
  },
];

export const resolveBuildProfile = (raw?: string): BuildProfile =>
  (raw || 'full').toLowerCase().trim() === 'internal' ? 'internal' : 'full';

export function discoverBackendRouteEntries(root: string): ProfileEntry[] {
  const backendRoot = path.join(root, 'src/app/(backend)');
  if (!fs.existsSync(backendRoot)) return [];

  const out: ProfileEntry[] = [];
  const walk = (dir: string) => {
    for (const name of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, name.name);
      if (name.isDirectory()) {
        walk(abs);
        continue;
      }
      if (name.name !== 'route.full.ts') continue;
      const internalAbs = path.join(dir, 'route.internal.ts');
      if (!fs.existsSync(internalAbs)) {
        throw new Error(`applyBuildProfile: missing route.internal.ts next to ${abs}`);
      }
      out.push({
        entry: path.relative(root, path.join(dir, 'route.ts')),
        full: './route.full',
        internal: './route.internal',
      });
    }
  };
  walk(backendRoot);
  return out.sort((a, b) => a.entry.localeCompare(b.entry));
}

export function listAllProfileEntries(root: string): ProfileEntry[] {
  return [...CORE_PROFILE_ENTRIES, ...discoverBackendRouteEntries(root)];
}

export function renderProfileEntry(entry: ProfileEntry, profile: BuildProfile): string {
  const reexport = profile === 'internal' ? entry.internal : entry.full;
  return `/* AUTO-GENERATED by scripts/applyBuildProfile.ts — do not edit.
 * profile=${profile}
 */
export * from '${reexport}';
`;
}

export function applyBuildProfile(root: string, profile: BuildProfile): ProfileEntry[] {
  const all = listAllProfileEntries(root);
  for (const e of all) {
    const abs = path.join(root, e.entry);
    const dir = path.dirname(abs);
    const reexport = profile === 'internal' ? e.internal : e.full;
    const candidates = [
      path.join(dir, reexport.replace(/^\.\//, '') + (e.kind === 'tsx' ? '.tsx' : '.ts')),
      path.join(dir, reexport.replace(/^\.\//, '') + '.ts'),
      path.join(dir, reexport.replace(/^\.\//, '') + '.tsx'),
    ];
    if (!candidates.some((c) => fs.existsSync(c))) {
      throw new Error(`applyBuildProfile: missing ${reexport} for ${e.entry}`);
    }
    fs.writeFileSync(abs, renderProfileEntry(e, profile));
  }
  return all;
}

/** Exact match against the canonical generated re-export body. */
export function entryPointsToProfile(
  entryBody: string,
  entry: ProfileEntry,
  profile: BuildProfile,
): boolean {
  return entryBody === renderProfileEntry(entry, profile);
}

export const INTERNAL_STUB_MESSAGE = 'Not available in this deployment profile';

/** Route-relative path segment → banned implementation markers in compiled chunks. */
export const ROUTE_BANNED_MARKERS: { match: RegExp; banned: string[] }[] = [
  {
    match: /create-image\/comfyui/,
    banned: ['comfyui.createImage', 'caller.comfyui', 'ComfyUIService'],
  },
  {
    match: /agent-eval-run/,
    banned: ['AgentEvalService', 'runBenchmark', 'serve<RunBenchmark'],
  },
  {
    match: /webhooks\/video/,
    banned: ['VideoGeneration', 'videoGeneration'],
  },
  {
    match: /market\//,
    banned: ['MarketService', 'marketService'],
  },
];

export function parseTurbopackChunkRefs(routeJs: string): string[] {
  const refs: string[] = [];
  for (const m of routeJs.matchAll(/R\.c\(\s*["']([^"']+)["']\s*\)/g)) {
    refs.push(m[1]!);
  }
  return refs;
}

export function resolveCompiledRouteJs(root: string, sourceRouteEntry: string): string | undefined {
  // source: src/app/(backend)/.../route.ts
  // compiled: .next/server/app/(backend)/.../route.js
  const rel = sourceRouteEntry.replace(/^src\/app\//, '').replace(/route\.ts$/, 'route.js');
  const candidates = [
    path.join(root, '.next/server/app', rel),
    path.join(root, '.next/standalone/.next/server/app', rel),
  ];
  return candidates.find((p) => fs.existsSync(p));
}

/**
 * Turbopack R.c("server/chunks/foo.js") is relative to the Next dist root
 * (.next / .next/standalone/.next), NOT to .next/server.
 */
export function resolveTurbopackChunk(
  root: string,
  ref: string,
  routeJsPath?: string,
): string | undefined {
  const bases = new Set<string>();
  // Prefer dist root inferred from the compiled route.js path
  if (routeJsPath) {
    const marker = `${path.sep}.next${path.sep}server${path.sep}`;
    const idx = routeJsPath.lastIndexOf(marker);
    if (idx !== -1) {
      bases.add(routeJsPath.slice(0, idx + `${path.sep}.next`.length));
    }
  }
  bases.add(path.join(root, '.next'));
  bases.add(path.join(root, '.next/standalone/.next'));

  for (const base of bases) {
    const abs = path.join(base, ref);
    if (fs.existsSync(abs)) return abs;
  }
  return undefined;
}

export type ChunkCollection = {
  graph: string;
  refs: string[];
  missingRefs: string[];
  resolvedPaths: string[];
};

export function collectChunkSources(root: string, routeJsPath: string): ChunkCollection {
  const routeJs = fs.readFileSync(routeJsPath, 'utf8');
  const refs = parseTurbopackChunkRefs(routeJs);
  const parts = [routeJs];
  const missingRefs: string[] = [];
  const resolvedPaths: string[] = [];

  for (const ref of refs) {
    const abs = resolveTurbopackChunk(root, ref, routeJsPath);
    if (!abs) {
      missingRefs.push(ref);
      continue;
    }
    resolvedPaths.push(abs);
    parts.push(fs.readFileSync(abs, 'utf8'));
  }

  return {
    graph: parts.join('\n'),
    refs,
    missingRefs,
    resolvedPaths,
  };
}
